[package]
name = "progrss"
version = "0.0.1"
edition = "2021"
authors = ["Tom Gouville <contact@tomgouville.fr>"]
description = "A clone of progress in Rust"
readme = "README.md"
repository = "https://github.com/aeyno/progrss"

[dependencies]
